datasource:
  master:
    url: jdbc:mariadb://15.164.213.202:9000/pickgit?serverTimezone=UTC&characterEncoding=UTF-8
    username: replication
    password: passwd
  slave:
    slave1:
      name: slave-1
      url: jdbc:mariadb://13.125.208.164:9000/pickgit?serverTimezone=UTC&characterEncoding=UTF-8
    slave2:
      name: slave-2
      url: jdbc:mariadb://13.125.250.121:9000/pickgit?serverTimezone=UTC&characterEncoding=UTF-8


