datasource:
  url: jdbc:mariadb://15.164.213.202:9000/pickgit?serverTimezone=UTC&characterEncoding=UTF-8
  username: replication
  password: passwd
  slave:
    slave1:
      name: slave-1
      url: jdbc:mariadb://13.125.208.164:9000/pickgit?serverTimezone=UTC&characterEncoding=UTF-8
      username: slave1
      password: passwd
    slave2:
      name: slave-2
      url: jdbc:mariadb://13.125.250.121:9000/pickgit?serverTimezone=UTC&characterEncoding=UTF-8
      username: slave2
      password: passwd

spring:
  jpa:
    properties:
      hibernate:
        show-sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        hbm2ddl:
          auto: create
    generate-ddl: true
